wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.9
    start_time: 1679065263.283795
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 53
      - 55
      3:
      - 7
      - 13
      - 15
      - 16
      - 19
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.001
