wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1681580869.792303
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.9.16
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 8
clip_duration:
  desc: null
  value: 15.0
loss_type:
  desc: null
  value: triplet
num_workers:
  desc: null
  value: 16
out_dim:
  desc: null
  value: 128
sample_rate:
  desc: null
  value: 16000
strides:
  desc: null
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
